# NumPy in Python


In [1]:
import numpy as np

In [2]:
arr=np.array([1,3,5,7,11], np.int8)
arr

array([ 1,  3,  5,  7, 11], dtype=int8)

______________________________**Array Creation in Python:**________________________________

In [3]:
myarr=np.array([[2,4,6],[1,3,5],[7,9,11],[8,10,12]])
myarr

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [ 8, 10, 12]])

In [4]:
myarr.shape

(4, 3)

In [5]:
myarr[0]

array([2, 4, 6])

In [6]:
myarr[1,0]=0
myarr

array([[ 2,  4,  6],
       [ 0,  3,  5],
       [ 7,  9, 11],
       [ 8, 10, 12]])

In [7]:
myarr.dtype

dtype('int32')

____________**Other Numpy:**____________

In [8]:
zeros=np.zeros((2,4))
zeros

#ones=np.ones((2,6))
#ones

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
ls= np.linspace(1,8,9)       
ls

array([1.   , 1.875, 2.75 , 3.625, 4.5  , 5.375, 6.25 , 7.125, 8.   ])

In [10]:
emp=np.empty((4,3))                                         #---generates randomly numbers in array
emp  

array([[1.40133492e-311, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 7.56592337e-307, 8.82515692e+169],
       [9.41716399e-047, 3.69982178e-057, 3.34716454e-061],
       [8.23615937e-067, 1.32681490e-047, 4.42609330e-062]])

In [50]:
empl=np.empty_like(ls)                     #---empty_like can be used we want to insert any previous array
empl

array([1.   , 1.875, 2.75 , 3.625, 4.5  , 5.375, 6.25 , 7.125, 8.   ])

In [12]:
id=np.identity(10)
id

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [13]:
id.shape

(10, 10)

In [14]:
rng=np.arange(30)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [15]:
rng.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [16]:
rng.ravel()                                                     #---1D array-in straight form

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
m=[[2,4,6],[1,3,5],[7,9,11],[8,10,12]]

In [18]:
ar=np.array(m)
ar

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [ 8, 10, 12]])

In [19]:
ar.sum(axis=0)                                                #---always 1 in rows 

array([18, 26, 34])

In [20]:
ar.sum(axis=1)                        #---always 0 in columns

array([12,  9, 27, 30])

In [21]:
ar.ndim                                    #---shows dimension (1D,2D)

2

In [22]:
ar.T                               #---taking transport

array([[ 2,  1,  7,  8],
       [ 4,  3,  9, 10],
       [ 6,  5, 11, 12]])

In [23]:
ar.nbytes                                                 #---total bytes using in given array

48

In [25]:
ar.argmax()                           #---showing maximum value at which index?

11

In [27]:
element=np.array([1,7,2,12,4])
element.argsort()                         #---gives sorted values at index

array([0, 2, 4, 1, 3], dtype=int64)

In [30]:
ar

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [ 8, 10, 12]])

In [28]:
ar.argmax(axis=0)                               #---looking from columns as axis is 0

array([3, 3, 3], dtype=int64)

In [29]:
ar.argmax(axis=1)                                     #---looking from rows as axis is 1

array([2, 2, 2, 2], dtype=int64)

In [43]:
ar1=np.array([[ 2,  0,  3],[ 1,  3,  4],[3,  0, 1],[0, 1, 2]])
ar1

array([[2, 0, 3],
       [1, 3, 4],
       [3, 0, 1],
       [0, 1, 2]])

__________________**Operations using NumPy**_____________________

In [45]:
ar+ar1                                                       #---using NumPy we can apply operators on list array.

array([[ 4,  4,  9],
       [ 2,  6,  9],
       [10,  9, 12],
       [ 8, 11, 14]])

In [46]:
ar*ar1

array([[ 4,  0, 18],
       [ 1,  9, 20],
       [21,  0, 11],
       [ 0, 10, 24]])

In [48]:
np.sqrt(ar)

array([[1.41421356, 2.        , 2.44948974],
       [1.        , 1.73205081, 2.23606798],
       [2.64575131, 3.        , 3.31662479],
       [2.82842712, 3.16227766, 3.46410162]])

In [49]:
np.where(ar>10)                     

(array([2, 3], dtype=int64), array([2, 2], dtype=int64))

In [51]:
import sys

In [52]:
py_ar=[1,2,3,4,5]

In [57]:
np_ar=np.array(py_ar)
sys.getsizeof(1) *len(py_ar)

140

In [58]:
np_ar.itemsize*np_ar.size                      #So less memory storage using numpy

20